---

name: CI/CD

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main"]
    tags: false
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: true
        default: 'warning'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pytest pylint

      - name: Run pytest
        run: |
          pytest tests/ -v

      - name: Run pylint
        run: |
          pylint src/martian_crud/ tests/ --exit-zero

      - name: Check Docker setup
        run: |
          docker --version
          docker buildx version
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/martian-crud:latest .

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main' 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/martian-crud:latest

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - run: echo "Deploying application..."
