---

name: CI/CD

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main"]
    tags: false
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: true
        default: 'warning'


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pylint

      - name: Run pytest
        run: |
          pytest tests/ -v
        # python -m
      - name: Run pylint
        run: |
          pylint src/ tests/ --exit-zero

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - run: echo "Deploying application..."
